import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createWorkbench} from '../bridge/service.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
test('project draft creates project start, selection creates no session, named sessions remain separate',async t=>{
 const temp=await mkdtemp(path.join(os.tmpdir(),'rab-named-flow-'));
 t.after(()=>rm(temp,{recursive:true,force:true}));
 const w=createWorkbench({root,rabHome:path.join(temp,'.rab')});
 assert.equal((await w.sessionNew()).status,'input-required');
 await assert.rejects(w.sessionTurn({text:'audit files'}),{code:'SESSION_REQUIRED'});
 let state=await w.sessionNew({draft:true});assert.equal(state.session_id,null);assert.ok(state.draft_id);
 assert.equal((await w.sessionList()).length,0);
 const source=path.join(temp,'source');await mkdir(source);
 for(const text of ['Start a new audit project','named-flow',source,'yes']) state=await w.sessionTurn({draft_id:state.draft_id,text});
 assert.ok(state.session_id);assert.equal(state.draft_id,null);
 const settings=JSON.parse(await readFile(path.join(state.rab.project,'sessions',String(state.session_id),'settings.json'),'utf8'));
 assert.equal(settings.name,'project start');
 assert.equal(state.groups.length,1);assert.ok(state.steps.some(step=>step.status==='completed'));
 const project_id=state.bag.project.id;
 const selected=await w.projectActivate({project_id,mode:'select'});assert.equal(selected.sessions.length,1);assert.equal(selected.session_id,null);
 assert.equal((await w.projectActivate({project_id,mode:'new-session'})).status,'input-required');
 assert.equal((await w.projectActivate({project_id,mode:'select'})).sessions.length,1);
 const next=await w.projectActivate({project_id,mode:'new-session',name:'Later audit'});assert.notEqual(next.session_id,state.session_id);assert.equal(next.groups.length,0);
 const viewed=await w.projectActivate({project_id,mode:'view',session_id:state.session_id});assert.equal(viewed.steps.length,state.steps.length);
 assert.equal((await w.projectActivate({project_id,mode:'select'})).sessions.length,2);
 const question=await w.sessionTurn({session_id:next.session_id,text:'start a new session'});assert.deepEqual(question.required_inputs,['name']);
 assert.equal((await w.projectActivate({project_id,mode:'select'})).sessions.length,2);
 const command=await w.sessionTurn({session_id:next.session_id,text:'start a new session named Follow-up'});assert.equal(command.name,'Follow-up');
});
