import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import { mkdir, mkdtemp, readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { run } from './beacons.mjs';

test('beacons preserve inputs, separate identities, validate choices and protect existing files', async () => {
  assert.ok(process.env.RAB_BOX_ROOT, 'Set RAB_BOX_ROOT to the Box source root.');
  const load = relative => import(pathToFileURL(path.join(process.env.RAB_BOX_ROOT, relative)));
  const { createRabMemory } = await load('bridge/rab-memory.mjs');
  const { makeItemSettings } = await load('bridge/rab-node.mjs');
  const { writeArtifactPlan } = await load('tools/_artifact-plan.mjs');
  const { createToolHouse } = await load('bridge/tool-house.mjs');
  const parent = path.join(os.homedir(), '.rab', 'tests');
  await mkdir(parent, { recursive: true });
  const fixture = await mkdtemp(path.join(parent, 'beacons-'));
  const root = path.join(fixture, 'source');
  await mkdir(root);
  const memory = createRabMemory({ rabHome: path.join(fixture, 'memory') });
  const tool = JSON.parse(await readFile(new URL('./settings.json', import.meta.url), 'utf8'));
  const helpers = { writeArtifactPlan, createItemSettings: async input => makeItemSettings({ ...input, id: await memory.allocateId() }) };
  const options = { name: 'admin-components', title: 'Administration Components', path: 'src/admin/components', description: 'Components with "quotes" and\nnewlines', types: ['ui', 'docs'] };
  const invoke = overrides => run({ options: { ...options, ...overrides }, context: { project: { root } }, tool, helpers });
  const bound = createToolHouse({ root: process.env.RAB_BOX_ROOT }).bindSettings(tool, options);
  assert.deepEqual(bound.missing, []);
  assert.equal(bound.options.beacon, 'on');
  assert.deepEqual(bound.options.reach, ['world', 'project']);
  assert.ok(createToolHouse({ root: process.env.RAB_BOX_ROOT }).bindSettings(tool, { ...options, path: undefined }).missing.some(field => field.name === 'path'));
  const result = await invoke({});
  const beacon = JSON.parse(await readFile(result.file, 'utf8'));
  assert.deepEqual(beacon, { id: beacon.id, ...options, date_added: beacon.date_added, beacon: 'on', reach: ['world', 'project'] });
  assert.equal(new Date(beacon.date_added).toISOString(), beacon.date_added);
  assert.ok(Number.isSafeInteger(beacon.id) && beacon.id > 0);
  assert.equal(result.verification.status, 'verified');
  assert.equal(result.file, path.join(root, 'src/admin/components/beacon.json'));
  const absolute = path.join(fixture, 'standalone');
  const standalone = await run({ options: { name: 'standalone', path: absolute }, tool, helpers });
  assert.equal(standalone.file, path.join(absolute, 'beacon.json'));
  assert.equal(standalone.beacon.path, absolute);
  assert.ok(Number.isSafeInteger(standalone.beacon.id));
  await assert.rejects(run({ options: { name: 'invalid', path: 'relative' }, tool, helpers }), { code: 'BAD_INPUT' });
  const minimal = await invoke({ path: 'minimal', title: undefined, description: undefined, types: undefined });
  assert.equal(minimal.beacon.title, options.name);
  assert.equal(minimal.beacon.description, '');
  assert.deepEqual(minimal.beacon.types, []);
  assert.deepEqual(tool.settings.filter(field => field.required).map(field => field.name), ['name', 'path']);
  const empty = await invoke({ path: 'empty', title: '', description: '', types: [] });
  assert.equal(empty.beacon.title, '');
  assert.deepEqual(empty.beacon.types, []);
  const functions = await invoke({ path: 'functions', types: ['functions'] });
  assert.deepEqual(functions.beacon.types, ['functions']);
  const second = await invoke({ path: 'src/shared/components', beacon: 'off', reach: ['project'] });
  assert.deepEqual(second.beacon.reach, ['project']);
  const worldOnly = await invoke({ path: 'world-only', reach: ['world'] });
  assert.deepEqual(worldOnly.beacon.reach, ['world']);
  const noReach = await invoke({ path: 'no-reach', reach: [] });
  assert.deepEqual(noReach.beacon.reach, []);
  assert.notEqual(second.beacon.id, beacon.id);
  assert.equal(second.beacon.beacon, 'off');
  await assert.rejects(invoke({}), { code: 'EEXIST' });
  assert.deepEqual(JSON.parse(await readFile(result.file, 'utf8')), beacon);
  for (const invalid of [{ reach: ['unknown'] }, { reach: ['world', 'world'] }, { reach: 'world' }, { title: false }, { types: ['unknown'] }, { types: ['ui', 'ui'] }, { path: '../escape' }, { path: 'C:/escape' }, { path: '' }, { beacon: false }]) {
    await assert.rejects(invoke(invalid), { code: 'BAD_INPUT' });
  }
  console.log(`Verified generated beacon: ${result.file}`);
});
