import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { mkdir, mkdtemp, readFile, writeFile, readdir, rename, symlink } from 'node:fs/promises';
const box=process.argv[2];
if (!box || !path.isAbsolute(box)) throw new Error('Supply the absolute Box installation folder.');
const {createToolHouse}=await import(pathToFileURL(path.join(box,'bridge/tool-house.mjs')).href);
const here=path.dirname(fileURLToPath(import.meta.url));
const testsRoot=path.join(os.homedir(),'.rab','temp','test');
await mkdir(testsRoot,{recursive:true});
const temp=await mkdtemp(path.join(testsRoot,'review-stamps-'));
const house=createToolHouse({root:temp,toolsRoot:path.resolve(here,'../../..')});
const key='model-kit/training/code-reviews';
const run=async (suffix,options)=>(await house.runTool({key:key+suffix,options})).result;
const rejected=async (action,codes)=>assert.rejects(action,error=>codes.includes(error.code));
const source=path.join(temp,'original');await mkdir(source);
const original='const text = "untouched";\r\n';
await writeFile(path.join(source,'original.js'),original);
const folder=path.join(temp,'session-one');
const session=await run('',{folder,original_source:source,title:'Quotes " and Unicode café'});
assert.equal(session.settings.original_source.path,source);
assert.equal(session.settings.title,'Quotes " and Unicode café');
assert.equal(session.settings.original_source.access,'read-only');
assert.equal(session.verification,'created-files-match-approved-plan-sha256');
assert.deepEqual((await readdir(folder)).sort(),['PROCESS.txt','README.txt','evaluations','presses','rounds','settings.json']);
const first=await run('/new-training-round',{session:folder,focus:''});
assert.equal(first.settings.number,1);assert.equal(first.settings.focus,'');
assert.equal(first.settings.session_id,session.id);
assert.equal(path.resolve(first.folder,first.settings.session_settings),path.join(folder,'settings.json'));
const evaluation=JSON.parse(await readFile(path.join(folder,'evaluations/evaluation.template.json'),'utf8'));
assert.equal(evaluation.split,'test');assert.equal(evaluation.contamination_review.status,'pending');
const press=JSON.parse(await readFile(path.join(folder,'presses/press.template.json'),'utf8'));
assert.equal(press.status,'planned');assert.equal(press.training.parameter_update_method,null);
assert.ok(press.evaluation.before);assert.ok(press.evaluation.after);
const lesson=JSON.parse(await readFile(path.join(first.folder,'lesson.template.json'),'utf8'));
assert.equal(lesson.status,'draft');assert.equal(lesson.approval,null);
assert.deepEqual(Object.keys(lesson).sort(),['schema_version','id','kind','status','messages','reason','source_ids','verification','approval'].sort());
const lessonReview=JSON.parse(await readFile(path.join(first.folder,'lesson-review.template.json'),'utf8'));
assert.equal(lessonReview.dataset_split,'unassigned');assert.equal(lessonReview.human_review,null);
const savedFirst=await readFile(path.join(first.folder,'settings.json'),'utf8');
const turn=JSON.parse(await readFile(path.join(first.folder,'turns','turn-001.json'),'utf8'));
assert.equal(turn.message,'');assert.equal(turn.status,'draft');assert.deepEqual(turn.code_blocks,[]);
const summary=JSON.parse(await readFile(path.join(first.folder,'summary.json'),'utf8'));
assert.equal(summary.approval,null);assert.equal(summary.verification.status,'not_tested');
// New rounds work with the external source offline; no source access is needed.
await rename(source,source+'-offline');
const second=await run('/new-training-round',{session:folder,title:'Second'});
assert.equal(second.settings.number,2);
await rename(source+'-offline',source);
await rename(second.folder,path.join(folder,'rounds','round-999'));
const thousand=await run('/new-training-round',{session:folder});
assert.equal(thousand.settings.number,1000);
assert.equal(path.basename(thousand.folder),'round-1000');
assert.equal(await readFile(path.join(first.folder,'settings.json'),'utf8'),savedFirst);
await rejected(()=>run('',{folder,original_source:source}),['EEXIST']);
await rejected(()=>run('',{folder:path.join(source,'inside'),original_source:source}),['INVALID_PATH']);
await rejected(()=>run('',{folder:'relative',original_source:source}),['INVALID_PATH']);
await rejected(()=>run('',{folder:path.join(temp,'con'),original_source:source}),['INVALID_INPUT']);
await rejected(()=>run('',{folder:path.join(temp,'missing-source'),original_source:path.join(temp,'absent')}),['ENOENT']);
await rejected(()=>run('',{}),['INPUT_REQUIRED','MISSING_SETTINGS']);
await rejected(()=>run('/new-training-round',{session:source}),['ENOENT']);
await writeFile(path.join(folder,'rounds','round-1001'),'collision');
await rejected(()=>run('/new-training-round',{session:folder}),['INVALID_ROUND']);
// Explicit access binding must not leak into saved source metadata.
const bound=await run('',{folder:path.join(temp,'bound-session'),original_source:'L:\\example-original',source_access:source});
assert.equal(bound.settings.original_source.path,'L:\\example-original');
assert.ok(!(await readFile(path.join(bound.folder,'settings.json'),'utf8')).includes(source.replaceAll('\\','\\\\')));
const boundSettings=path.join(bound.folder,'settings.json');
const altered=JSON.parse(await readFile(boundSettings,'utf8'));altered.rounds.path='../outside';await writeFile(boundSettings,JSON.stringify(altered));
await rejected(()=>run('/new-training-round',{session:bound.folder}),['INVALID_SESSION']);
const link=path.join(temp,'linked-original');await symlink(source,link,'junction');
await rejected(()=>run('',{folder:path.join(temp,'linked-session'),original_source:link}),['INVALID_PATH']);
assert.equal(await readFile(path.join(source,'original.js'),'utf8'),original);
const catalog=await house.listTools({fresh:true});
assert.ok(catalog.items.some(t=>t.key===key));assert.ok(catalog.items.some(t=>t.key===key+'/new-training-round'));
const report={status:'passed',temp,checks:['session and round output','JSON escaping','separate source binding','original bytes unchanged','offline source round creation','numbering and gaps through 1000','earlier rounds unchanged','draft/approval defaults','existing destination refusal','missing/invalid inputs','overlapping folders','path traversal','junction refusal','shared-runner discovery']};
await writeFile(path.join(temp,'verification.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
