import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { readFile,writeFile,mkdir,mkdtemp,readdir,rename,unlink } from 'node:fs/promises';
import { fileURLToPath,pathToFileURL } from 'node:url';
const box=process.argv[2];
const {createToolHouse}=await import(pathToFileURL(path.join(box,'bridge/tool-house.mjs')).href);
const here=path.dirname(fileURLToPath(import.meta.url));
const temp=await mkdtemp(path.join(os.homedir(),'.rab/temp/test/capture-check-'));
const house=createToolHouse({root:temp,toolsRoot:path.resolve(here,'../../..')});
const key='model-kit/training/code-reviews';
const run=async(suffix,options)=>(await house.runTool({key:key+suffix,options})).result;
const original=path.join(temp,'original'),working=path.join(temp,'working'),session=path.join(temp,'session');
await mkdir(original);await mkdir(working);await writeFile(path.join(original,'archive.zip'),'original archive fixture');
await writeFile(path.join(working,'a.ts'),'const a = 1;\r\n');
await writeFile(path.join(working,'unchanged.ts'),'unchanged\n');
await run('',{folder:session,original_source:original});
const settingsFile=path.join(session,'settings.json');const settings=JSON.parse(await readFile(settingsFile));settings.working_copy={path:working};await writeFile(settingsFile,JSON.stringify(settings));
await run('/new-training-round',{session});
const capture=options=>run('/capture-change',{session,...options});
await capture({action:'baseline'});
const objects=path.join(session,'evidence/objects');assert.equal((await readdir(objects)).length,2);
await assert.rejects(()=>capture({action:'baseline'}),e=>e.code==='EEXIST');
await assert.rejects(()=>capture({action:'finish'}),e=>e.code==='NO_ACTIVE_CHANGE');
await capture({action:'begin',round:'round-001',reason:'Split responsibilities',source_turns:['turns/turn-001.json']});
await assert.rejects(()=>capture({action:'begin',round:'round-001',reason:'Second'}),e=>e.code==='CHANGE_ACTIVE');
await writeFile(path.join(working,'a.ts'),'export {a} from "./b";\n');
await writeFile(path.join(working,'b.ts'),'export const a = 1;\n');
const first=await capture({action:'finish'});assert.equal(first.changed_files.length,2);
assert.equal((await readdir(objects)).length,4);
const change=JSON.parse(await readFile(path.join(session,first.change,'completed/changes.json')));
for(const item of change.changes)for(const version of [item.before,item.after])if(version)assert.equal((await readFile(path.join(objects,version.sha256))).length,version.bytes);
const a=change.changes.find(x=>x.file==='a.ts');assert.equal((await readFile(path.join(objects,a.before.sha256))).toString(),'const a = 1;\r\n');
assert.ok((await readFile(path.join(session,first.change,'completed/change.patch'),'utf8')).includes('export {a}'));
await capture({action:'begin',round:'round-001',reason:'Rename and add binary'});
await rename(path.join(working,'b.ts'),path.join(working,'renamed.ts'));
await writeFile(path.join(working,'image.bin'),Buffer.from([0,255,1,13,10]));
const second=await capture({action:'finish',renames:[{from:'b.ts',to:'renamed.ts'}]});assert.equal(second.renames.length,1);
assert.equal((await readdir(objects)).length,5);
assert.ok((await readFile(path.join(session,second.change,'completed/change.patch'),'utf8')).includes('GIT binary patch'));
await writeFile(path.join(working,'untracked.ts'),'oops');
await assert.rejects(()=>capture({action:'begin',round:'round-001',reason:'Missing capture'}),e=>e.code==='UNTRACKED_CHANGE');
await unlink(path.join(working,'untracked.ts'));
await capture({action:'begin',round:'round-001',reason:'No edit'});const noChange=await capture({action:'finish'});assert.equal(noChange.changed_files.length,0);
assert.equal((await readdir(objects)).length,5);
await capture({action:'begin',round:'round-001',reason:'Integrity check'});
const object=path.join(objects,a.after.sha256);const saved=await readFile(object);await writeFile(object,'corrupt');
await assert.rejects(()=>capture({action:'finish'}),e=>e.code==='CORRUPT_EVIDENCE');await writeFile(object,saved);
await capture({action:'finish'});
assert.equal((await readFile(path.join(original,'archive.zip'))).toString(),'original archive fixture');
assert.equal((await capture({action:'status'})).state.active,null);
const report={status:'passed',temp,checks:['baseline','exact CRLF bytes','split across files','created/deleted paths','explicit rename','binary snapshot and patch','deduplicated unchanged versions','no archive copies','active-change guard','uncaptured drift refusal','tamper detection','no-change capture','source unchanged']};
await writeFile(path.join(temp,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
